apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: logistics-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: logistics.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gateway-svc
            port:
              number: 80
